server:
  port: 8002
spring:
  application:
    name: xinhao-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinhao_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:com/lizi123/xinhao/mapper/*Mapper.xml
  type-aliases-package: com.lizi123.xinhao.domain,com.lizi123.xinhao.query,com.lizi123.xinhao.mapper,com.lizi123.xinhao.controller,com.lizi123.xinhao.service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true