server:
  port: 9527
spring:
  application:
    name: xinhao-zuul-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    
    